[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jsonutils"
    version = "@project.version@"
    path = "../jsonutils-native/build/libs/jsonutils-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["jsonutils"]

    [[platform.libraries]]
    artifactId = "jsonutils"
    version = "@project.version@"
    path = "../jsonutils-test-utils/build/libs/jsonutils-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.jsonutils"
    modules = ["jsonutils"]
    scope = "testOnly"
